### ISSUE TITLE
[ Init ] 기본 세팅

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#1]
## 💡 Feature Issue
초기 세팅입니다.

## 🌿  To-do
🐰 @xionng 
- [x] 초기 세팅 (패키지 설치)
- [x] reset.css, global.css 추가

🐱 @hyun907 
- [ ] eslint, prettier 설정
- [ ] 폴더 구조화
