### ISSUE TITLE
[ Feat ] 에너지 효율 등급에 따른 디자인 변경

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#104]
## 💡 Feature Issue
에너지 효율 등급에 따른 디자인 변경 이슈입니다.

## 🌿  To-do
- [x] 에너지 효율 등급 변경 시 가전 페이지 초록색 아이콘
- [x] 가전 추가 페이지 + 밀림 CSS 해결
- [x] 에너지 효율 등급 변경 시 상세 페이지

### 에너지 효율 등급 변경 시 가전 페이지 초록색 아이콘
<img width="297" alt="image" src="https://github.com/user-attachments/assets/7ba4381d-dabf-4179-8d23-121587b099b0">

### 에너지 효율 등급 변경 시 상세 페이지
<img width="242" alt="image" src="https://github.com/user-attachments/assets/a11afdb4-0c6a-4506-a826-1435ffc56d41">
