### ISSUE TITLE
[ Feat ] 가전 히스토리 페이지, 효율등급 변경 시 가전 Circle Border 그라데이션

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#107]
## 💡 Feature Issue
가전 효율등급 히스토리 페이지 추가
가전 효율등급 변경 시 가전 Circle Border 그라데이션 적용
이슈입니다.

## 🌿  To-do
- [ ] 가전 등급 히스토리 페이지 추가
- [ ] 가전 페이지에서 알람 아이콘 누르면 히스토리 페이지로 들어갈 수 있도록 연결
- [ ] 등급 변경 시 Border에 그라데이션 적용

### 히스토리 페이지
<img width="255" alt="image" src="https://github.com/user-attachments/assets/9af79b5f-2954-40ca-a0f3-266cdb4d6e8a">

### Border 색 변경
<img width="406" alt="image" src="https://github.com/user-attachments/assets/86a15a2e-c7fc-4c52-91a2-0ca549226e39">
