### ISSUE TITLE
[ Refactor ] 마무리 수정

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#116]
## 🌿  To-do

- [ ] 기프티콘 순서 바꾸기
- [ ] 포인트 내역 기간별 정렬
- [ ] 포인트 내역 단위 설정 및 -, + 간격 조정
- [ ] 팝업 오버레이 투명도 통일
- [ ] 에너지 퀴즈 상단바 gotohome으로 수정
