### ISSUE TITLE
[ Fix ] 4차 QA (1) 

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#124]
## 📝 리팩토링 설명
백과 페이지 - 에너지 백과 이모티콘과 버튼 사이가 너무 비어있는 느낌 → 세션 가운데 정렬
가전제품 리스트 페이지 - 가전제품 메모 기능에서, 50자를 꽉 채워서 입력했을때 칸을 넘어감
가전제품 추가 페이지 - 추가하기 버튼을 하단에 고정하기, 현재는 가전이 많을 시에 스크롤을 아래로 끝까지 내려서 추가해야하는 불편함이 있음
가전제품 추가 페이지 - 툴팁 z-index 수정
홈 - 출석체크시 뜨는 모달에서 현재 보유 포인트가 1450p로 고정되어 있음 → 유저 현재 포인트로 변경

## 🌿  To-do
- [x] 백과 페이지 - 에너지 백과 세션 가운데 정렬
- [x] 가전제품 리스트 페이지 - 가전제품 메모 기능에서, 50자를 꽉 채워서 입력 시 칸 넘어감 CSS
- [x] 가전제품 추가 페이지 - 추가하기 버튼 하단에 고정
- [x] 가전제품 추가 페이지 - 툴팁 z-index 수정
- [x] 홈 - 출석체크시 뜨는 모달 유저 현재 포인트로 변경

## 📚 ETC
notion 참고
