### ISSUE TITLE
[ Refactor ]4차 QA 후 수정

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#127]
## 🌿  To-do

- [x] 파워 - 예상요금 차트 글씨 위치 수정
- [x] 파워- 예상요금 차트 멘트 수정
- [x] 파워 - 파워 입력 바텀시트 멘트 수정
- [x] 파워 - 입력 페이지 년도 헤더부분 어긋남 수정
- [x] 홈- 퀴즈 박스 멘트 수정
- [x] 마이-  내정보수정 알림 토스트로 변경
