### ISSUE TITLE
[ Refactor ]4차 QA 후 수정2

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#133]
## 🌿  To-do

- [x] 퀴즈 박스 좀 내리기
- [ ] 기프티콘 편지 추가
- [ ] 기타 디자인 수정
