### ISSUE TITLE
[ Feat ] 파워 그래프 컴포넌트 디자인 퍼블리싱

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#21]
## 💡 Feature Issue

파워 그래프 컴포넌트 디자인 퍼블리싱 관련 이슈입니다.

## 🌿  To-do

- [x] 기본 그래프 요소 제작
- [x] 그래프 스타일 지정
- [x] 데이터 없을 때 기본 화면 제작

## 📚 ETC

![스크린샷 2024-10-21 01 17 48](https://github.com/user-attachments/assets/5de878ff-732a-4b1d-af94-1d19b4113ee3)
