### ISSUE TITLE
[ Feat ] 로그인 페이지 디자인 퍼블리싱

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#27]
## 💡 Feature Issue

로그인 디자인 퍼블리싱 관련 이슈입니다.

## 🌿  To-do

- [x] 랜딩페이지 레이아웃 제작
- [x] 납부일, 거주자수 입력 페이지 레이아웃 제작
- [ ] 최종 디자인 적용

## 📚 ETC

![스크린샷 2024-10-30 15 15 04](https://github.com/user-attachments/assets/5068710d-7348-46ce-bf1c-f7007bd40369)
![스크린샷 2024-10-30 15 15 08](https://github.com/user-attachments/assets/76e4d8af-cec2-4307-ab70-701dc1e03a9d)
