### ISSUE TITLE
[ Refactor ] 1차 배포 후 css 수정

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#37]
## 📝 리팩토링 설명

1차 배포 후 모바일에서 실행했을때 css 문제가 있어서 해당 부분 수정하려고 합니다.
## 🌿  To-do

- [x] 홈, 파워 페이지 전체 스크롤
- [x] 버튼 텍스트 크기(글씨 넘어가는 문제)
- [x] 하단바 라우트 연결
