### ISSUE TITLE
[ Refactor ] 파워페이지 전체 디자인 수정

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#44]
## 🌿  To-do

- [ ] 그래프 컴포넌트 수정
- [ ] 파워 입력 버튼 수정
- [ ] 예상요금+저번달 요금 기능 합치기
