### ISSUE TITLE
[ Feat ] 가전 페이지 Open API 부분 연결

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#48]
## 💡 Feature Issue
가전 페이지 Open API 연결

## 🌿  To-do
- [ ] 가전 제품 검색
- [ ] 가전 제품 추가
- [ ] 가전 제품 상세 보기
