### ISSUE TITLE
[ Bug ] 2차 QA 후 기능 수정

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#54]
## 📝 에러 설명

1. 파워-예상요금 차트 부분 입력 안한 달을 0 그대로 인식
2. 전전월, 전월 둘 다 입력 없을 시에 팁 멘트 렌더링 안됨 이슈
3. 파워 입력 후 새로고침 이슈
4. 홈화면 버튼 라우터 연결

## 🌿  To-do

- [x] 파워 예상요금 차트 이슈 해결
- [ ] 파워 입력 새로고침 이슈 해결
- [x] 홈화면의 버튼 라우터 연결
- [x] 예상요금 차트 모션 추가
- [x] 로딩 화면 추가
