### ISSUE TITLE
[ Refactor ] 2차 QA 반영 (3등급 조건부 글씨 색변경, 로딩 공통 페이지 추가, 가전제품 페이지 레이아웃)

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#57]
## 📝 리팩토링 설명
- 3등급이 노란색 배경 디자인이라, 글씨 색을 어둡게 변경하는 작업
- 로딩 공통 페이지 추가
- 가전제품 페이지 그리드 맞추기

## 🌿  To-do
- [ ] 3등급 조건부로 색 변경
- [ ] loading.tsx 추가
- [ ] 가전제품 페이지 그리드 맞추기

## 📚 ETC
<img width="323" alt="image" src="https://github.com/user-attachments/assets/86bd6a6f-9e10-4ab0-b196-c430dee8e082">
