### ISSUE TITLE
[ Refactor ]2차 QA 후 2차 수정(입력 멘트 수정, 드롭다운 년도 적용)

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#59]
## 📝 리팩토링 설명

2차 QA 후 2차 수정입니다.

## 🌿  To-do

- [x] 입력, 파워 리포트 멘트 수정
- [x] 파워 입력 년도 드롭다운 적용
- [x] 파워 팁 멘트 말풍선 크기 변경
- [x] 파워 입력 + 버튼 위치 조정
