### ISSUE TITLE
[ Refactor ] 2차 QA 수정 (가전 제품 중복 추가, 제품 예외처리)

### ISSUE THREAD

**Issue by hyun907** [GreenSpark-greenspark/greenspark-frontend#60]
## 📝 리팩토링 설명

1. 가전 - 내 가전제품 등록시 중복일 경우 프론트에서 토스트 문구 변경: “이미 추가된 가전제품입니다!” (백엔드에서는 이미 db에 있는 가전제품 추가 시에 에러 뜨게 처리해서 해당 에러 시 토스트가 나옵니다.) 현재는 추가되었다는 토스트와 함께 추가 로직까지 되지만 실제적으로 추가 기능까지는 안 되는 상태입니다.
2. 가전 - 가전제품 검색 시 글자가 길어서 짤리는건지, 제대로 보이지 않는 것 같습니다.
3. 가전 이미지 매핑
## 🌿  To-do
- [ ] 중복 (기존에 있어서 에러가 올 경우) 시 분기 처리 -> 토스트가 뜨면서 추가 화면 안 뜨게
- [ ] 가전제품 중에 길게 오는 제품들, 예를 들어 공기청정기 (~24.12.31)처럼 오픈 api 자체에서 응답이 기간까지 함께 오는 경우 고려
- [ ] 케이스 별 가전 이미지 매핑

## 📚 ETC
<img width="429" alt="image" src="https://github.com/user-attachments/assets/dd42e00f-fa29-4d07-a0e2-a6f2c1692d15">
