### ISSUE TITLE
[ Refactor ]3차 QA 후 수정(파워 입력 버튼, 그래프 멘트 수정)

### ISSUE THREAD

**Issue by xionng** [GreenSpark-greenspark/greenspark-frontend#71]
## 🌿  To-do

- [x] 파워 입력 버튼 수정
- [x] 그래프 안내 멘트 수정
- [x] 예상요금 api 연결 수정
- [x] 파워 입력 테이블 헤드 고정되도록
- [ ] 지난달, 예상요금 차트 클릭되게 수정
- [x] 스크롤 문제 해결
- [x] 파워 입력 상한선 설정
- [x] 다크모드 스타일 무시하도록 설정
